version: "3"
services:
  es-poem-search-system:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.1
    container_name: vietnamese_poem_search_system_es
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    volumes:
      - es_data_poem_search_system:/usr/share/elasticsearch/data

volumes:
  es_data_poem_search_system:
